{% set name = "handcalcs" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/handcalcs-{{ version }}.tar.gz
  sha256: e7f47c72faee829310dd61de94ad7bb1d20a1003243611a1706b828a826eb28d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit
  run:
    - innerscope >=0.7.0
    - more-itertools
    - pyparsing
    - python >={{ python_min }}

test:
  imports:
    - handcalcs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/connorferster/handcalcs
  summary: Converts your Python calculation script into beautifully rendered Latex,
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - connorferster
    - jan-janssen
